getCustomers:
    path: /
    controller: App\Controller\CustomersController::getCustomers

getEmployees:
    path: /
    controller: App\Controller\EmployeesController::getEmployees

getOffices:
    path: /
    controller: App\Controller\OfficesController::getOffices

getOrders:
    path: /
    controller: App\Controller\OrdersController::getOrders

getPayments:
    path: /
    controller: App\Controller\PaymentsController::getPayments

getProductLines:
    path: /
    controller: App\Controller\ProdcutLinesController::getProductLines

getProducts:
    path: /
    controller: App\Controller\ProdcutsController::getProducts
